### ISSUE TITLE
Show GitHub profile link of every contributor in the release notes

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito-release-tools#12]
Current [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md) list the authors which is great because it motivates to contribute! However, the author is listed by name, without the link to GitHub profile. The profile would be useful for more exposure / fame for the contributors.

Last time I worked on it, there was no way to link user to GitHub profile.

TODO:
 - try to find GitHub user name given that we have Git author/author email. Engage community, ask on GitHub tracker, ask on twitter, etc.
 - as suggested by @TimvdLippe we can use GitHub search API: https://api.github.com/search/users?q=tvanderlippe@gmail.com&in=email

🚀 Looking for help!!!

If you like to party, try to implement this interface and submit a pull request! :) To get started, run "GitHubTicketFetcherTest" test, it actually hits GitHub to get data.

```java
/**
 * Maps Git authors to GitHub users 
 */
public interface GitHubUserMapper {

    /**
     * Provides mapping from Git author email to GitHub user name.
     * 
     * @param authorEmails email addresses of git authors
     */
    Map<String, String> mapToGitHubUser(Collection<String> authorEmails);
}
```

**Comment by mstachniuk** [comment]
I think it's better to search by login, NOT by e-mail. Search by e-mail doesn't work if you change **Public e-mail** to "Don't show my e-mail address" in Github settings page. I think this is better way: https://api.github.com/search/users?q=TimvdLippe&in=login

**Comment by mstachniuk** [comment]
I looked into the code and GitHub API a little bit. Generating notes has 2 sources of true: 

1. `git log` for read commits and 
2. GitHub API `/issues` for read info about solved issues.

In first case we can read user git name and e-mail and from second source we can read GitHub login (`user.login`) and GitHub user URL (`user. html_url`). We can use this data to link to user profile in release notes, but sometimes we are unable to match this two informations (GitHub login can be differ from git user name). 

Also we are unable to read link to GitHub profile from commits: https://developer.github.com/v3/git/commits/ We see only the same information like in `git log` i.e. name and e-mail.

I didn't ask on GitHub tracker / twitter.

**Comment by szczepiq** [comment]
Hey! Long time no hear :)

When the release automation is getting git log, we don't have access to the GitHub login (we have Git user name and email). Some users might have the same GitHub login as Git user name but it's unlikely. Hence, search by email is probably the best given circumstances.

Do you want to help out with the implementation? When you clone and open the project in IDEA, run "GitHubTicketFetcherTest" test. The test actually hits GitHub.

Thanks for suggestions!!!

**Comment by szczepiq** [comment]
If you like to party, try to implement this interface :). To get started, run "GitHubTicketFetcherTest" test.

```java
/**
 * Maps Git authors to GitHub users 
 */
public interface GitHubUserMapper {

    /**
     * Provides mapping from Git author email to GitHub user name.
     * 
     * @param authorEmails email addresses of git authors
     */
    Map<String, String> mapToGitHubUser(Collection<String> authorEmails);
}
```

**Comment by mstachniuk** [comment]
You're welcome!

As I said in my first comment, searching by e-mail will usually not work, try this: https://api.github.com/search/users?q=szczepiq@gmail.com&in=email (I found your e-mail using GH API, you can delete this comment if you don't like to publish it ;) ).

Unfortunately this is a gap in GH API that we can't easy link commit author with GH page author. I see a few solutions.

Solution 1. GitHub team will add link to user profile in `/commits` endpoint (generation notes will be slowly because of possible big number of needed requests).

Solution 2. We can read GH profile link from `/issuses` (see: https://api.github.com/repos/mockito/mockito/issues?state=closed&filter=all&labels=&direction=desc generated by `GitHubTicketFetcher.GitHubIssues.GitHubIssues(...)`) and link only to creators of PullRequest using GitHub login and link to profile. See result of this API call: https://api.github.com/users/szczepiq then we will see in release notes something like this: [szczepiq](https://github.com/szczepiq)

Solution 3. GH team will add to `/issuses` git name, or in https://api.github.com/users/szczepiq or somewhere else, then we can generate notes like this: [Szczepan Faber](https://github.com/szczepiq)

Solution 4. We can use Github UI instead of API and get this information from HTML. But then change in UI can destroy everything.

I can implement something, but maybe it's better to first ask GitHub team for improvement in the API?

**Comment by szczepiq** [comment]
Thank you for researching!

4) is impractical, 2) will not match accurately (user assigned / changing issue not necessarily is the implementor)

How about using search API, e.g. searching for commits: https://developer.github.com/v3/search/#search-commits

**Comment by mstachniuk** [comment]
The search API is in developers preview and it's hard to reduce results to reasonable size. 
A little bit better looks commit API: https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository
e.g.:
https://api.github.com/repos/mockito/mockito/commits

It's also hard to limit results, but reading sha of commits from `git log` can help us to match authors with GitHub profile pages. I can implement this. 

I asked also GitHub API support for few improvements from this thread.

**Comment by szczepiq** [comment]
Great work @mstachniuk, we're about to use it in Mockito: https://github.com/mockito/mockito/pull/987

THANKS!!!
